### ISSUE TITLE
bug: event emit gives `error: Variable was previously moved.`

### ISSUE THREAD

**Issue by tarrencev** [starkware-libs/cairo#2116]
# Bug Report

**Cairo version:**

`b51c511ab39dae631362d4157853db46c2c49d64`

**Current behavior:**

emitting the following event:

```
    #[event]
    fn ComponentValueSet(component_id: felt, entity_id: felt, data: Array::<felt>) {}

    ...

    #[external]
    fn on_component_set(entity_id: felt, data: Array::<felt>) {
        ComponentValueSet(caller_address_felt, entity_id, data);
    }
```

results in the error

```
error: Variable was previously moved.
 --> contract:143:9
        serde::Serde::<felt>::serialize(ref data, entity_id);
        ^**************************************************^
```

compiled contract looks like:

```
    #[event]
    fn ComponentValueSet(component_id: felt, entity_id: felt, data: Array::<felt>) {
        let mut keys = array_new();
        array_append(ref keys, 0x20427dbf22fa80ffee4e42a5864b7fd37b9f906cc4db230d084faa3a0ce558f);
        let mut data = array_new();
        serde::Serde::<felt>::serialize(ref data, component_id);
        serde::Serde::<felt>::serialize(ref data, entity_id);
        serde::Serde::<Array::<felt>>::serialize(ref data, data);
        
        starknet::emit_event_syscall(keys, data).unwrap_syscall()
    }
```

<img width="707" alt="image" src="https://user-images.githubusercontent.com/4740651/218516370-5912a463-73e2-4095-a8db-41eb5e55866a.png">

full repo at: https://github.com/dojoengine/dojo/pull/51

**Comment by tarrencev** [comment]
This is resolved with https://github.com/starkware-libs/cairo/pull/2117/

**Comment by spapinistarkware** [comment]
The issue here is the reuse of the 'data' reserved var, right?
I don't think Array should have Copy. It should have explicit clone, but that won't solve this issue.

If we had hermetic plugin generation like in rust, that would solve all these name reuse issues, or maybe just a better pattern for writing these plugins.

For now, the concrete immediate solution is to use _data in the plugin.

**Comment by msaug** [comment]
> I don't think Array should have Copy

So a good practice would be to always pass arrays by reference in functions if we want to reuse it in multiple instructions rather than passing by value which takes ownership? Just trying to figure out how everything works together 😄 
If so I can modify my PR to remove the Copy implementation and only keep the Drop ones for common integer array types.
