### ISSUE TITLE
bug: Can't execute release binaries

### ISSUE THREAD

**Issue by unparalleled-js** [starkware-libs/cairo#2261]
# Bug Report

Release binaries are only available on Linux?

**Cairo version:**

1.0.0-alpha.3

**Current behavior:**

From macOS x86, when trying to run the binaries from the release, I get this error:

```
zsh: exec format error:
```

I have also tried with `bash` and got a similar error.

**Expected behavior:**

Can run binaries from my OS as well as my friend Jane's OS.

**Steps to reproduce:**

* Download release from GitHub
* Attempt to execute a binary. It fails saying it is wrong format or something.

**Related code:**

```bash
./starknet-compile
```

**Other information:**

**Comment by cwkang1998** [comment]
Are you downloading the release ` release-x86_64-unknown-linux-musl.tar.gz `? If so then it'll not work as expected on macOS since its not built for it.

To get it working for macOS, you can build it yourself by cloning the code down and doing `cargo build`, or run directly with `cargo run --bin starknet-compile`.

**Comment by spapinistarkware** [comment]
If this is a feature request, describe it as such

**Comment by unparalleled-js** [comment]
> If this is a feature request, describe it as such

I figured "Any Linux" applied to MacOS but I see that I am wrong. I would have chosen another issue template had I known. Still, I feel like you get the gist of my request and I am not going to open another ticket.
