### ISSUE TITLE
bug: PartialEq should get a snapshot, instead of owned values

### ISSUE THREAD

**Issue by spapinistarkware** [starkware-libs/cairo#2975]
We should change that signaure of `PartialEq` at `traits.cairo` to get `@T` instead of `T`, and fix everything that breaks

**Comment by Jinwei1987** [comment]
maybe I could help with this issue, is this issue being picked by anyone?

**Comment by spapinistarkware** [comment]
You can certainly help, yes, it;s not yet assigned

**Comment by Jinwei1987** [comment]
Sure, let me give a go

**Comment by Jinwei1987** [comment]
after changing T to @T, for boolean it depends on 
extern fn bool_eq(lhs: bool, rhs: bool) -> bool implicits() nopanic;

what is the best approach to convert @T to T for primitive types, maybe a clone?
Or do we want to change the underlying bool_eq to accept the snapshot @bool

**Comment by spapinistarkware** [comment]
Just use a desnap operator (*)

**Comment by Jinwei1987** [comment]
Yeah, thanks. I figured out myself as well. Just same as Rust.

**Comment by Jinwei1987** [comment]
after making T to @T, what is the best practice to compare snapshot with literal constants, i.e. 0_u32?

**Comment by spapinistarkware** [comment]
It should not be different.
0==1 should still work. It should just translate to PartialEq::eq(@0,@1)

If you want to compare a:@usize and b:usize, like before, u do *a==b

**Comment by Jinwei1987** [comment]
PartialEq<u32> will translate into @0 == @1, in order to make 0==1 work, I have to add eq(u32, u32) and ne(u32, u32) without a trait right?

**Comment by Jinwei1987** [comment]
In Rust PartialEq signature uses reference, but it works with non-borrowed values, i.e. 0 == 1. When I change T to @T in PartialEq in Cairo, non-borrowed values will not compiled, i.e. 0 == 1 will fail to compile. I think  in Rust they do some special work on operator ==, let it always use reference. Does it mean we need to the similar thing in Cairo, so that 0 == 1 will automatically work with @T signature? 

@abdelhamidbakhta I am happy to continue to work with this issue. But I am new to the project, and may have some trouble to estimate the complexity of the work.

**Comment by Jinwei1987** [comment]
looks like this issue has been fixed. Better to close it :)
