### ISSUE TITLE
Use of remove_original_item

### ISSUE THREAD

**Issue by taco-paco** [starkware-libs/cairo#3066]
https://github.com/starkware-libs/cairo/blob/ee9a0bb1e496c6e5d922c3a5071d85b45f8bc268/crates/cairo-lang-defs/src/db.rs#L310

This comment states:
> The first one to change something (either generate new code, remove the original code, or both), breaks the loop

But in almost all occurrences `remove_original_code` is set too false even if new code is generated. [derive.rs](https://github.com/starkware-libs/cairo/blob/ee9a0bb1e496c6e5d922c3a5071d85b45f8bc268/crates/cairo-lang-plugins/src/plugins/derive.rs#L196), [panicable.rs](https://github.com/starkware-libs/cairo/blob/ee9a0bb1e496c6e5d922c3a5071d85b45f8bc268/crates/cairo-lang-plugins/src/plugins/panicable.rs#L135) and so on, except of code generated for contract. Is that a bug or there are more conditions for `remove_original_code` being `true`?

**Comment by taco-paco** [comment]
Also had a question why are we iterating over plugins [here](https://github.com/starkware-libs/cairo/blob/ee9a0bb1e496c6e5d922c3a5071d85b45f8bc268/crates/cairo-lang-defs/src/db.rs#L313) but not over attributes of an item and then mapping it to some plugin and executing `generate_code`?

**Comment by orizi** [comment]
it isn't a bug - it is a feature for cases where we do want to remove the original item (i currently indeed is only for contract stuff).

Since a plugin is not based on attributes at all in the general case - it tends to be - but nothing enforces it.
You can install a plugins that deletes all the written code - it would have nothing to do with attributes.
