### ISSUE TITLE
feat: support providing user input into Cairo program

### ISSUE THREAD

**Issue by etaligarium** [starkware-libs/cairo#3870]
# Feature Request

**Describe the Feature Request**

I would like to ask for a feature that allows the user to provide inputs to the cairo program, and also, specify the visibility of the inputs. For instance, in the senario of checking that the total assets of a person is greater than a certain amount, the user can input the total assets into the cairo program, and the cairo program also specifies that the total assets should be private and not visible to the verifier.

Also, I have checked other zero-knowledge proof libraries, and I found that they all support this feature. For instance, in the [Noir](https://noir-lang.org/), the user can specify a public input to the program by the keyword `pub`, as can be seen in the following example:

```rust
fn main(x : Field, y : pub Field) {
    assert(x != y);
}
```

**Describe Preferred Solution**

1. The cairo program should support inputs to the entry function.
2. The cairo program should support specifying the visibility of the inputs.
3. cairo-run should support providing inputs to the cairo program.

**Describe Alternatives**

**Related Code**

A piece of code similar to the following example should be supported by the cairo program:

```rust
fn main(x : felt252, y : pub felt252) {
    assert(x != y);
}
```

The `pub` keyword specifies that the variable `y` is a public input to the program. Inputs without the `pub` keyword are private inputs to the program.

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [x] No

**Comment by ArielElp** [comment]
The compiler is independent of how the program will be used, e.g., you can eventually prove the execution of a Cairo program in zk or not (ATM the SHARP prover is not zk in the formal sense).

In the future, we can add something analogous to `serialize_word` in CairoZero, which added an element to the public memory section of the program (note again that if the prover is not ZK you may leak information about the non-public memory section as well). Since `serialize_word` is not usable in the context of Starknet smart contracts, this is not a priority for the near future. You can track the roadmap [here](https://github.com/orgs/starkware-libs/projects/1).
