### ISSUE TITLE
bug: InvalidFunctionApChange error when compiling Sierra to CASM with gas tracking disabled

### ISSUE THREAD

**Issue by m-kus** [starkware-libs/cairo#6612]
# Bug Report

**Cairo version:**

v2.9.0

**Current behavior:**

Compiler fails with `AnnotationError(InvalidFunctionApChange { statement_idx: StatementIdx(90219), expected: Enabled { ap_change: 0, base: FunctionStart }, actual: Disabled })`

**Expected behavior:**

Compiler exits without errors.

**Steps to reproduce:**

```
git clone https://github.com/keep-starknet-strange/raito
cd raito
scarb --profile cairo1-run cairo-run --package client '[[]]'
```

Also:

https://github.com/m-kus/cairo/pull/2/files contains unit test which reproduces the issue

**Additional info:**

The problem seems to be in that `cairo_lang_sierra_to_casm::metadata::calc_metadata_ap_change_only` (used when `gas_usage_check` is `false`) produces different AP change data compared to `cairo_lang_sierra_to_casm::metadata::calc_metadata`.  

In the given example they differ exactly in one `function_ap_change` item which has AP change = 0.

On the other hand `cairo_lang_sierra_to_casm::environment::ap_tracking::update_ap_tracking` sets the AP tracking for the corresponding function to `Disabled` likely because there is `disable_ap_tracking` call along the way.

In the result, when `cairo_lang_sierra_to_casm::annotations::validate_return_properties` is called, the expected AP change (from metadata) doesn't match the actual value.

**Potential fix**

A quick fix that worked for me is to filter out zero solutions here: https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra-ap-change/src/lib.rs#L116-L125

But I'm worried that it might be fixing symptoms rather than the cause.

**Comment by orizi** [comment]
`calc_metadata_ap_change_only` is supposed to return different results to `calc_metadata` (as there are no gas actions added, so there's no ap fixes for them) - so that isn't the particular issue - but in any case - a function with 0 ap-change is very suspicious.

Can you tell me which function was the problematic one?

Thanks!

**Comment by orizi** [comment]
It seems i found the issue - it seems the old version of ap-change solution is used when no gas calculation is requested, and since it wasn't used anywhere in production it was not checked.

Attached PR changes the solver - it solves your failing attached sierra file.

if you can check if this works for your scarb build as well - would be appreciated.

Thanks again!

**Comment by m-kus** [comment]
Checked with the Scarb project, compiles/runs without errors 👍 
Thank you!
